In [1]:
import pandas as pd
import numpy as np

In [2]:
nparr = np.array([[1,22,3,36]])

In [3]:
nparr[0,3]

np.int64(36)

In [4]:
nparr.shape

(1, 4)

In [5]:
nparr.dtype

dtype('int64')

In [6]:
nparr[0,3] = 89  # this changed the value

In [7]:
nparr

array([[ 1, 22,  3, 89]])

In [8]:
lspace = np.linspace(1,4,3)   # it prints 3 elements bet 1 to 4 and keep spacing [duri] of all with all equal

In [9]:
lspace

array([1. , 2.5, 4. ])

In [10]:
arr = np.arange(99) # this creates an array of 0 to 98 value all 99 digits

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [12]:
arr.reshape(3,33)  # this reshapes a defined array into specific multiple like 99 = 3*33 so  3 subrrays will there of 33 elements in each

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [13]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [14]:
array = np.array(x)

In [15]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
array.sum(axis = 1) # sums up the rows

array([ 6, 15, 24])

In [17]:
array.sum(axis = 0) # sums up the columns

array([12, 15, 18])

In [18]:
array.flat

In [19]:
for items in array.flat:
    print(items)

1
2
3
4
5
6
7
8
9


In [20]:
array.ndim  # tell the dimension of array

2

In [21]:
one = np.array([1,24,53,454,34])

In [22]:
one

array([  1,  24,  53, 454,  34])

In [23]:
one.argmax() # bracket means as an funciton it is executed and tell the position of max element

np.int64(3)

In [24]:
one.argmin() # tells min

np.int64(0)

In [25]:
one.argsort()  # only tells the sorted array position how it should be

array([0, 1, 4, 2, 3])

In [26]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
array.argmax() # checks full array and gives max

np.int64(8)

In [28]:
array.argmax(axis = 1) # checks columns

array([2, 2, 2])

In [29]:
array.argmin(axis = 0) # checks with rows

array([0, 0, 0])

In [30]:
array.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [31]:
array.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [32]:
array.ravel() # gives in straight line

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
array.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [34]:
array.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr2 = np.array([[4, 7, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [39]:
array + arr2

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [40]:
array * arr2

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

In [46]:
np.where(array > 2)  # give o/p like array ka (rows), (columns)  0 ka row n 2nd column

(array([0, 1, 1, 1, 2, 2, 2]), array([2, 0, 1, 2, 0, 1, 2]))

In [47]:
type(np.where(array > 2) )

tuple

In [48]:
np.count_nonzero(array)

np.int64(9)